---
- name: Build and test libffi
  hosts: all
  gather_facts: true
  tasks:
    - name: Delete old working directory
      file:
        path: $HOME/libffi-{{ host_triple }}
        state: absent

    - name: Create working directory
      file:
        path: $HOME/libffi-{{ host_triple }}/build
        state: directory

    - name: Clone libffi source
      git:
        repo: 'https://github.com/libffi/libffi.git'
        dest: $HOME/libffi-{{ host_triple }}/libffi

    - name: Prepare the source
      command: ./autogen.sh
      args:
        chdir: $HOME/libffi-{{ host_triple }}/libffi

    - name: Configure the source
      command: ../libffi/configure
      args:
        chdir: $HOME/libffi-{{ host_triple }}/libffi

    - name: Build
      command: make
      args:
        chdir: $HOME/libffi-{{ host_triple }}/libffi
